In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

In [4]:
from sklearn import preprocessing
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn import datasets
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score, train_test_split, cross_val_predict

In [5]:
# Sklearn regression model evaluation functions
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

### Carga de dataset preprocesado

In [6]:
df = pd.read_csv('df_to_model_1.csv')

In [7]:
df

Unnamed: 0  transactioned   types    skin  \
0              0              1  Female     Mid   
1              1              1    Male    Dark   
2              2              0  Female   Light   
3              3              0    Male    Dark   
4              4              0    Male     Mid   
...          ...            ...     ...     ...   
9995        9995              0  Female  Albino   
9996        9996              0    Male   Light   
9997        9997              0  Zombie  Zombie   
9998        9998              0  Female     Mid   
9999        9999              0  Female    Dark   

                                               traits  human  rarity  \
0                 Blonde Bob,Earring,Green Eye Shadow      1    2023   
1                                        Mohawk,Smile      1    4352   
2                                           Wild Hair      1    8090   
3                         Nerd Glasses,Pipe,Wild Hair      1    7896   
4                   Big Shades,Earring,Goat,Wild Hair      1    7332   
...                                               ...    ...     ...   
9995             Purple Eye Shadow,Straight Hair Dark      1    2466   
9996               Cigarette,Crazy Hair,Earring,Smile      1    4323   
9997                          Cap Forward,Front Beard      0     498   
9998  Black Lipstick,Clown Eyes Green,Wild White Hair      1    1271   
9999                              Mohawk,Nerd Glasses      1    9233   

      traits_range  hidden_traits_range  amount_ethereum    Eth_to_$  
0                1                    2             25.0  112.880000  
1                1                    2             60.0  605.083333  
2                2                    2              NaN         NaN  
3                1                    2              NaN         NaN  
4                1                    2              NaN         NaN  
...            ...                  ...              ...         ...  
9995             1                    2              NaN         NaN  
9996             1                    2              NaN         NaN  
9997             1                    2              NaN         NaN  
9998             1                    2              NaN         NaN  
9999             1                    2              NaN         NaN  

[10000 rows x 11 columns]

# Pre-procesamiento adicional requerido por particularidades del modelo de regresión logística

### Conversión de variables categóricas en Dummy

In [8]:
dummy = pd.get_dummies(data=df, columns=['types', 'skin'])

In [9]:
dummy

Unnamed: 0  transactioned  \
0              0              1   
1              1              1   
2              2              0   
3              3              0   
4              4              0   
...          ...            ...   
9995        9995              0   
9996        9996              0   
9997        9997              0   
9998        9998              0   
9999        9999              0   

                                               traits  human  rarity  \
0                 Blonde Bob,Earring,Green Eye Shadow      1    2023   
1                                        Mohawk,Smile      1    4352   
2                                           Wild Hair      1    8090   
3                         Nerd Glasses,Pipe,Wild Hair      1    7896   
4                   Big Shades,Earring,Goat,Wild Hair      1    7332   
...                                               ...    ...     ...   
9995             Purple Eye Shadow,Straight Hair Dark      1    2466   
9996               Cigarette,Crazy Hair,Earring,Smile      1    4323   
9997                          Cap Forward,Front Beard      0     498   
9998  Black Lipstick,Clown Eyes Green,Wild White Hair      1    1271   
9999                              Mohawk,Nerd Glasses      1    9233   

      traits_range  hidden_traits_range  amount_ethereum    Eth_to_$  \
0                1                    2             25.0  112.880000   
1                1                    2             60.0  605.083333   
2                2                    2              NaN         NaN   
3                1                    2              NaN         NaN   
4                1                    2              NaN         NaN   
...            ...                  ...              ...         ...   
9995             1                    2              NaN         NaN   
9996             1                    2              NaN         NaN   
9997             1                    2              NaN         NaN   
9998             1                    2              NaN         NaN   
9999             1                    2              NaN         NaN   

      types_Alien  ...  types_Female  types_Male  types_Zombie  skin_Albino  \
0               0  ...             1           0             0            0   
1               0  ...             0           1             0            0   
2               0  ...             1           0             0            0   
3               0  ...             0           1             0            0   
4               0  ...             0           1             0            0   
...           ...  ...           ...         ...           ...          ...   
9995            0  ...             1           0             0            1   
9996            0  ...             0           1             0            0   
9997            0  ...             0           0             1            0   
9998            0  ...             1           0             0            0   
9999            0  ...             1           0             0            0   

      skin_Alien  skin_Ape  skin_Dark  skin_Light  skin_Mid  skin_Zombie  
0              0         0          0           0         1            0  
1              0         0          1           0         0            0  
2              0         0          0           1         0            0  
3              0         0          1           0         0            0  
4              0         0          0           0         1            0  
...          ...       ...        ...         ...       ...          ...  
9995           0         0          0           0         0            0  
9996           0         0          0           1         0            0  
9997           0         0          0           0         0            1  
9998           0         0          0           0         1            0  
9999           0         0          1           0         0            0  

[1000

# Pre-procesamiento para Modelo 1

### Eliminación de variables no relevantes para modelo 1

In [10]:
model_1 = dummy.drop(columns=['Unnamed: 0', 'traits', 'human', 'amount_ethereum', 'Eth_to_$'])

In [11]:
model_1

transactioned  rarity  traits_range  hidden_traits_range  types_Alien  \
0                 1    2023             1                    2            0   
1                 1    4352             1                    2            0   
2                 0    8090             2                    2            0   
3                 0    7896             1                    2            0   
4                 0    7332             1                    2            0   
...             ...     ...           ...                  ...          ...   
9995              0    2466             1                    2            0   
9996              0    4323             1                    2            0   
9997              0     498             1                    2            0   
9998              0    1271             1                    2            0   
9999              0    9233             1                    2            0   

      types_Ape  types_Female  types_Male  types_Zombie  skin_Albino  \
0             0             1           0             0            0   
1             0             0           1             0            0   
2             0             1           0             0            0   
3             0             0           1             0            0   
4             0             0           1             0            0   
...         ...           ...         ...           ...          ...   
9995          0             1           0             0            1   
9996          0             0           1             0            0   
9997          0             0           0             1            0   
9998          0             1           0             0            0   
9999          0             1           0             0            0   

      skin_Alien  skin_Ape  skin_Dark  skin_Light  skin_Mid  skin_Zombie  
0              0         0          0           0         1            0  
1              0         0          1           0         0            0  
2              0         0          0           1         0            0  
3              0         0          1           0         0            0  
4              0         0          0           0         1            0  
...          ...       ...        ...         ...       ...          ...  
9995           0         0          0           0         0            0  
9996           0         0          0           1         0            0  
9997           0         0          0           0         0            1  
9998           0         0          0           0         1            0  
9999           0         0          1           0         0            0  

[10000 rows x 16 columns]

### División entre train y test datasets

In [12]:
train, test = train_test_split(model_1, test_size = 0.2, random_state=42)

### Definición de X y y para Modelo 1

In [13]:
X_train = train.drop(columns = ['transactioned'], axis=1).values
y_train = train['transactioned'].values

In [14]:
X_train

array([[2589,    1,    2, ...,    1,    0,    0],
       [2670,    1,    2, ...,    0,    0,    0],
       [5436,    1,    2, ...,    0,    0,    0],
       ...,
       [5572,    1,    2, ...,    1,    0,    0],
       [1412,    1,    2, ...,    1,    0,    0],
       [5182,    1,    2, ...,    0,    0,    0]], dtype=int64)

In [15]:
y_train

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [16]:
X_test = test.drop(columns = ['transactioned'], axis=1).values
y_test = test['transactioned'].values

In [17]:
X_test

array([[ 812,    1,    2, ...,    0,    1,    0],
       [7502,    1,    2, ...,    0,    0,    0],
       [4728,    1,    2, ...,    0,    0,    0],
       ...,
       [2744,    1,    2, ...,    1,    0,    0],
       [6482,    1,    2, ...,    1,    0,    0],
       [2138,    1,    2, ...,    1,    0,    0]], dtype=int64)

In [18]:
y_test

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

### Estandariación de variables numéricas: Rarity, Traits_range y hidde_traits_range

In [19]:
scaler = StandardScaler()

In [20]:
X_train = scaler.fit_transform(X_train)

In [21]:
X_test = scaler.fit_transform(X_test)

In [22]:
X_train

array([[-0.83334364, -0.18867619, -0.01500169, ...,  1.53437208,
        -0.66108978, -0.0959637 ],
       [-0.80525956, -0.18867619, -0.01500169, ..., -0.6517324 ,
        -0.66108978, -0.0959637 ],
       [ 0.15375967, -0.18867619, -0.01500169, ..., -0.6517324 ,
        -0.66108978, -0.0959637 ],
       ...,
       [ 0.20091319, -0.18867619, -0.01500169, ...,  1.53437208,
        -0.66108978, -0.0959637 ],
       [-1.24142955, -0.18867619, -0.01500169, ...,  1.53437208,
        -0.66108978, -0.0959637 ],
       [ 0.06569355, -0.18867619, -0.01500169, ..., -0.6517324 ,
        -0.66108978, -0.0959637 ]])

In [23]:
y_train

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [24]:
X_test

array([[-1.45695144, -0.20145155, -0.02236627, ..., -0.67106358,
         1.53117001, -0.08692914],
       [ 0.85255061, -0.20145155, -0.02236627, ..., -0.67106358,
        -0.65309534, -0.08692914],
       [-0.10508148, -0.20145155, -0.02236627, ..., -0.67106358,
        -0.65309534, -0.08692914],
       ...,
       [-0.7899921 , -0.20145155, -0.02236627, ...,  1.49017177,
        -0.65309534, -0.08692914],
       [ 0.50042922, -0.20145155, -0.02236627, ...,  1.49017177,
        -0.65309534, -0.08692914],
       [-0.99919364, -0.20145155, -0.02236627, ...,  1.49017177,
        -0.65309534, -0.08692914]])

In [25]:
y_test

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

# Pre-procesamiento para Modelo 2: Reemplazo de Types y Skin por Human

In [31]:
model_2 = df.drop(columns=['Unnamed: 0', 'traits', 'types', 'skin', 'amount_ethereum', 'Eth_to_$'])

In [32]:
model_2

transactioned  human  rarity  traits_range  hidden_traits_range
0                 1      1    2023             1                    2
1                 1      1    4352             1                    2
2                 0      1    8090             2                    2
3                 0      1    7896             1                    2
4                 0      1    7332             1                    2
...             ...    ...     ...           ...                  ...
9995              0      1    2466             1                    2
9996              0      1    4323             1                    2
9997              0      0     498             1                    2
9998              0      1    1271             1                    2
9999              0      1    9233             1                    2

[10000 rows x 5 columns]

### División entre train y test datasets

In [33]:
train2, test2 = train_test_split(model_2, test_size = 0.2, random_state=42)

### Definición de X y y para Modelo 2

In [34]:
X_train2 = train2.drop(columns = ['transactioned'], axis=1).values
y_train2 = train2['transactioned'].values

In [35]:
X_train2

array([[   1, 2589,    1,    2],
       [   1, 2670,    1,    2],
       [   1, 5436,    1,    2],
       ...,
       [   1, 5572,    1,    2],
       [   1, 1412,    1,    2],
       [   1, 5182,    1,    2]], dtype=int64)

In [36]:
y_train2

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [37]:
X_test2 = test2.drop(columns = ['transactioned'], axis=1).values
y_test2 = test2['transactioned'].values

In [38]:
X_test2

array([[   1,  812,    1,    2],
       [   1, 7502,    1,    2],
       [   1, 4728,    1,    2],
       ...,
       [   1, 2744,    1,    2],
       [   1, 6482,    1,    2],
       [   1, 2138,    1,    2]], dtype=int64)

In [39]:
y_test2

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

### Estandariación de variables numéricas: Rarity, Traits_range y hidde_traits_range

In [40]:
scaler = StandardScaler()

In [41]:
X_train2 = scaler.fit_transform(X_train2)

In [42]:
X_test2 = scaler.fit_transform(X_test2)

In [43]:
X_train2

array([[ 0.11364269, -0.83334364, -0.18867619, -0.01500169],
       [ 0.11364269, -0.80525956, -0.18867619, -0.01500169],
       [ 0.11364269,  0.15375967, -0.18867619, -0.01500169],
       ...,
       [ 0.11364269,  0.20091319, -0.18867619, -0.01500169],
       [ 0.11364269, -1.24142955, -0.18867619, -0.01500169],
       [ 0.11364269,  0.06569355, -0.18867619, -0.01500169]])

In [44]:
y_train2

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [45]:
X_test2

array([[ 0.09793424, -1.45695144, -0.20145155, -0.02236627],
       [ 0.09793424,  0.85255061, -0.20145155, -0.02236627],
       [ 0.09793424, -0.10508148, -0.20145155, -0.02236627],
       ...,
       [ 0.09793424, -0.7899921 , -0.20145155, -0.02236627],
       [ 0.09793424,  0.50042922, -0.20145155, -0.02236627],
       [ 0.09793424, -0.99919364, -0.20145155, -0.02236627]])

In [46]:
y_test2

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

# Implementación de Decision Tree Classifier

## Modelo 1

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
# Create Decision Tree classifer object
dtc = DecisionTreeClassifier()

# Train Decision Tree Classifer
dtc = dtc.fit(X_train,y_train)

In [28]:
# Create Decision Tree classifer object
dtc = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
dtc = dtc.fit(X_train,y_train)

#Predict the response for test dataset
y_pred_dtc = dtc.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_dtc))

print('Evaluación calidad Modelo')

predictions_dtc = dtc.predict(X_test)
mae_dtc = round(mean_absolute_error(y_test, predictions_dtc), 4)
rmse_dtc = round(sqrt(mean_squared_error(y_test, predictions_dtc)), 4)
r2_dtc = round(r2_score(y_test, predictions_dtc), 4)

print("    MAE", round(mean_absolute_error(y_test, predictions_dtc), 4))
print("    RMSE", round(sqrt(mean_squared_error(y_test, predictions_dtc)), 4))
print("    R2", round(r2_score(y_test, predictions_dtc), 4))

Accuracy: 0.555
Evaluación calidad Modelo
    MAE 0.445
    RMSE 0.6671
    R2 -0.7923


In [48]:
print('Evaluación calidad Modelo')
print('---------------------------')
print('---------------------------')
print('Confusion Matrix')
print('---------------------------')
print('---------------------------')
print(confusion_matrix(y_test, predictions_dtc))
print('---------------------------')
print('---------------------------')
print('Classif Report')
print('---------------------------')
print('---------------------------')
print(classification_report(y_test, predictions_dtc))

Evaluación calidad Modelo
---------------------------
---------------------------
Confusion Matrix
---------------------------
---------------------------
[[327 590]
 [300 783]]
---------------------------
---------------------------
Classif Report
---------------------------
---------------------------
              precision    recall  f1-score   support

           0       0.52      0.36      0.42       917
           1       0.57      0.72      0.64      1083

    accuracy                           0.56      2000
   macro avg       0.55      0.54      0.53      2000
weighted avg       0.55      0.56      0.54      2000



## Modelo 2

In [47]:
# Create Decision Tree classifer object
dtc = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
dtc = dtc.fit(X_train2,y_train2)

#Predict the response for test dataset
y_pred_dtc2 = dtc.predict(X_test2)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test2, y_pred_dtc2))

print('Evaluación calidad Modelo')

predictions_dtc2 = dtc.predict(X_test2)
mae_dtc = round(mean_absolute_error(y_test2, predictions_dtc2), 4)
rmse_dtc = round(sqrt(mean_squared_error(y_test2, predictions_dtc2)), 4)
r2_dtc = round(r2_score(y_test2, predictions_dtc2), 4)

print("    MAE", round(mean_absolute_error(y_test2, predictions_dtc2), 4))
print("    RMSE", round(sqrt(mean_squared_error(y_test2, predictions_dtc2)), 4))
print("    R2", round(r2_score(y_test2, predictions_dtc2), 4))

Accuracy: 0.5555
Evaluación calidad Modelo
    MAE 0.4445
    RMSE 0.6667
    R2 -0.7903


In [49]:
print('Evaluación calidad Modelo')
print('---------------------------')
print('---------------------------')
print('Confusion Matrix')
print('---------------------------')
print('---------------------------')
print(confusion_matrix(y_test2, predictions_dtc2))
print('---------------------------')
print('---------------------------')
print('Classif Report')
print('---------------------------')
print('---------------------------')
print(classification_report(y_test2, predictions_dtc2))

Evaluación calidad Modelo
---------------------------
---------------------------
Confusion Matrix
---------------------------
---------------------------
[[263 654]
 [235 848]]
---------------------------
---------------------------
Classif Report
---------------------------
---------------------------
              precision    recall  f1-score   support

           0       0.53      0.29      0.37       917
           1       0.56      0.78      0.66      1083

    accuracy                           0.56      2000
   macro avg       0.55      0.53      0.51      2000
weighted avg       0.55      0.56      0.53      2000



# Implementación de Random Forest

## Modelo 1

In [50]:
rfc = RandomForestClassifier(n_estimators = 10, random_state=32) 
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=32)

In [51]:
# Create Decision Tree classifer object
rfc = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
rfc = rfc.fit(X_train,y_train)

#Predict the response for test dataset
y_pred_rfc = rfc.predict(X_test)


In [54]:
print('Evaluación calidad Modelo')
print('---------------------------')
print('---------------------------')
print('Confusion Matrix')
print('---------------------------')
print('---------------------------')
print(confusion_matrix(y_test, y_pred_rfc))
print('---------------------------')
print('---------------------------')
print('Classif Report')
print('---------------------------')
print('---------------------------')
print(classification_report(y_test, y_pred_rfc))

Evaluación calidad Modelo
---------------------------
---------------------------
Confusion Matrix
---------------------------
---------------------------
[[327 590]
 [300 783]]
---------------------------
---------------------------
Classif Report
---------------------------
---------------------------
              precision    recall  f1-score   support

           0       0.52      0.36      0.42       917
           1       0.57      0.72      0.64      1083

    accuracy                           0.56      2000
   macro avg       0.55      0.54      0.53      2000
weighted avg       0.55      0.56      0.54      2000



# Implementación de Modelo de Regresión Logística

## Modelo 1

In [55]:
# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train,y_train)

y_lg_pred=logreg.predict(X_test)

In [56]:
print('Evaluación calidad Modelo')
print('---------------------------')
print('---------------------------')
print('Confusion Matrix')
print('---------------------------')
print('---------------------------')
print(confusion_matrix(y_test, y_lg_pred))
print('---------------------------')
print('---------------------------')
print('Classif Report')
print('---------------------------')
print('---------------------------')
print(classification_report(y_test, y_lg_pred))

Evaluación calidad Modelo
---------------------------
---------------------------
Confusion Matrix
---------------------------
---------------------------
[[164 753]
 [134 949]]
---------------------------
---------------------------
Classif Report
---------------------------
---------------------------
              precision    recall  f1-score   support

           0       0.55      0.18      0.27       917
           1       0.56      0.88      0.68      1083

    accuracy                           0.56      2000
   macro avg       0.55      0.53      0.48      2000
weighted avg       0.55      0.56      0.49      2000



# Implementación de Modelo K Nearest Neighbors Classifier

In [57]:
from sklearn.neighbors import KNeighborsClassifier
kneighbors = KNeighborsClassifier(n_neighbors=5)
kneighbors.fit(X_train, y_train)
y_knc_pred=logreg.predict(X_test)

In [58]:
print('Evaluación calidad Modelo')
print('---------------------------')
print('---------------------------')
print('Confusion Matrix')
print('---------------------------')
print('---------------------------')
print(confusion_matrix(y_test, y_knc_pred))
print('---------------------------')
print('---------------------------')
print('Classif Report')
print('---------------------------')
print('---------------------------')
print(classification_report(y_test, y_knc_pred))

Evaluación calidad Modelo
---------------------------
---------------------------
Confusion Matrix
---------------------------
---------------------------
[[164 753]
 [134 949]]
---------------------------
---------------------------
Classif Report
---------------------------
---------------------------
              precision    recall  f1-score   support

           0       0.55      0.18      0.27       917
           1       0.56      0.88      0.68      1083

    accuracy                           0.56      2000
   macro avg       0.55      0.53      0.48      2000
weighted avg       0.55      0.56      0.49      2000

